# Generated by Django 4.1.4 on 2024-01-23 22:18

import django.utils.timezone
import django_s3_storage.storage
import walletapp.utils
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("walletapp", "0072_alter_currencies_picture_large_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="collections",
            name="created_timestamp",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="collections",
            name="images_zip_files",
            field=models.FileField(
                blank=True,
                help_text="Where to upload zip file containing collection",
                null=True,
                storage=django_s3_storage.storage.S3Storage(
                    aws_s3_bucket_name="django-images-testnet"
                ),
                upload_to=walletapp.utils.get_media_images_zip_file,
            ),
        ),
        migrations.AddField(
            model_name="collections",
            name="status",
            field=models.CharField(
                choices=[
                    (
                        "waiting_for_miting_transactions",
                        "Waiting for minting transactions",
                    ),
                    ("minted", "Minted"),
                    ("error", "Error"),
                ],
                default="minted",
                help_text="Status of the minting transaction",
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="collections",
            name="updated_timestamp",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="currencies",
            name="picture_large",
            field=models.ImageField(
                blank=True,
                help_text="Small icon representing the asset",
                null=True,
                storage=django_s3_storage.storage.S3Storage(
                    aws_s3_bucket_name="django-images-testnet"
                ),
                upload_to=walletapp.utils.get_media_path_large,
            ),
        ),
        migrations.AlterField(
            model_name="currencies",
            name="picture_orig",
            field=models.ImageField(
                blank=True,
                help_text=(
                    "Image representing the asset. Please upload a square image about"
                    " 800x800 in size. Images will be rescaled."
                ),
                null=True,
                storage=django_s3_storage.storage.S3Storage(
                    aws_s3_bucket_name="django-images-testnet"
                ),
                upload_to=walletapp.utils.get_media_path_orig,
            ),
        ),
        migrations.AlterField(
            model_name="currencies",
            name="picture_small",
            field=models.ImageField(
                blank=True,
                help_text="Large icon representing the asset",
                null=True,
                storage=django_s3_storage.storage.S3Storage(
                    aws_s3_bucket_name="django-images-testnet"
                ),
                upload_to=walletapp.utils.get_media_path_small,
            ),
        ),
    ]
