# Generated by Django 4.1.4 on 2024-01-23 22:23

import django_s3_storage.storage
import walletapp.utils
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("walletapp", "0073_collections_created_timestamp_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="collections",
            name="images_zip_file",
            field=models.FileField(
                blank=True,
                help_text="Where to upload zip file containing collection",
                null=True,
                storage=django_s3_storage.storage.S3Storage(
                    aws_s3_bucket_name="django-images-testnet"
                ),
                upload_to=walletapp.utils.get_media_images_zip_file,
            ),
        ),
    ]
