# Generated by Django 4.1.4 on 2024-01-23 22:26

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("walletapp", "0075_remove_collections_images_zip_files"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="collections",
            name="created_timestamp",
        ),
        migrations.RemoveField(
            model_name="collections",
            name="updated_timestamp",
        ),
    ]
