# Generated by Django 4.1.4 on 2024-01-23 22:27

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("walletapp", "0076_remove_collections_created_timestamp_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="collections",
            name="created_timestamp",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="collections",
            name="updated_timestamp",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
