# Generated by Django 4.1.4 on 2024-01-24 01:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("walletapp", "0077_collections_created_timestamp_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="collections",
            name="created_timestamp",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="collections",
            name="updated_timestamp",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AddConstraint(
            model_name="collections",
            constraint=models.UniqueConstraint(
                fields=("name",), name="collection_name_unique"
            ),
        ),
    ]
