# Generated by Django 4.1.4 on 2023-01-30 10:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("walletapp", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="currencies",
            name="genesis_bootstrap_info",
            field=models.CharField(
                default="",
                help_text="Genesis bootstrap info. Required for creating an invoice",
                max_length=1000,
                unique=True,
            ),
        ),
    ]
