# Generated by Django 4.1.4 on 2023-01-30 10:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("walletapp", "0002_alter_currencies_genesis_bootstrap_info"),
    ]

    operations = [
        migrations.AlterField(
            model_name="currencies",
            name="genesis_bootstrap_info",
            field=models.CharField(
                default="",
                help_text="Genesis bootstrap info. Required for creating an invoice",
                max_length=1000,
            ),
        ),
    ]
