# Generated by Django 4.1.4 on 2023-01-31 09:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("walletapp", "0003_alter_currencies_genesis_bootstrap_info"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="currencies",
            name="picture_url",
        ),
        migrations.AddField(
            model_name="currencies",
            name="is_nft",
            field=models.BooleanField(
                blank=True,
                default=False,
                help_text="Indicates if the currency is a NFT or not",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="currencies",
            name="picture_large",
            field=models.ImageField(
                default="", help_text="Small icon representing the asset", upload_to=""
            ),
        ),
        migrations.AddField(
            model_name="currencies",
            name="picture_small",
            field=models.ImageField(
                default="", help_text="Image representing the asset", upload_to=""
            ),
        ),
        migrations.AlterField(
            model_name="currencies",
            name="genesis_bootstrap_info",
            field=models.CharField(
                default="",
                help_text="Genesis bootstrap info. Required for creating an invoice",
                max_length=1000,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="currencies",
            name="owner",
            field=models.ForeignKey(
                blank=True,
                help_text="Owner of the asset",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
