# Generated by Django 4.1.4 on 2023-01-31 09:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("walletapp", "0004_remove_currencies_picture_url_currencies_is_nft_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="currencies",
            name="picture_large",
            field=models.ImageField(
                default="",
                help_text="Small icon representing the asset",
                upload_to="currencies_small",
            ),
        ),
        migrations.AlterField(
            model_name="currencies",
            name="picture_small",
            field=models.ImageField(
                default="",
                help_text="Image representing the asset",
                upload_to="currencies_small",
            ),
        ),
    ]
