# Generated by Django 4.1.4 on 2023-01-31 09:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("walletapp", "0005_alter_currencies_picture_large_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="currencies",
            name="picture_large",
            field=models.ImageField(
                blank=True,
                default="",
                help_text="Small icon representing the asset",
                null=True,
                upload_to="currencies_small",
            ),
        ),
        migrations.AlterField(
            model_name="currencies",
            name="picture_small",
            field=models.ImageField(
                blank=True,
                default="",
                help_text="Image representing the asset",
                null=True,
                upload_to="currencies_small",
            ),
        ),
    ]
