# Generated by Django 4.1.4 on 2023-01-31 10:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("walletapp", "0006_alter_currencies_picture_large_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="currencies",
            name="picture_large",
            field=models.ImageField(
                blank=True,
                default="currencies_large/default.png",
                help_text="Small icon representing the asset",
                null=True,
                upload_to="currencies_small",
            ),
        ),
        migrations.AlterField(
            model_name="currencies",
            name="picture_small",
            field=models.ImageField(
                blank=True,
                default="currencies_large/default.png",
                help_text="Image representing the asset",
                null=True,
                upload_to="currencies_large",
            ),
        ),
    ]
