# Generated by Django 4.1.4 on 2023-02-01 11:03

import django_s3_storage.storage
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("walletapp", "0010_alter_currencies_picture_large_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="currencies",
            name="picture_orig",
            field=models.ImageField(
                blank=True,
                help_text="Image representing the asset",
                null=True,
                storage=django_s3_storage.storage.S3Storage(
                    aws_s3_bucket_name="django-images-testnet"
                ),
                upload_to="uploads/currencies_orig",
            ),
        ),
        migrations.AlterField(
            model_name="currencies",
            name="picture_large",
            field=models.ImageField(
                blank=True,
                help_text="Small icon representing the asset",
                null=True,
                storage=django_s3_storage.storage.S3Storage(
                    aws_s3_bucket_name="django-images-testnet"
                ),
                upload_to="uploads/currencies_small",
            ),
        ),
        migrations.AlterField(
            model_name="currencies",
            name="picture_small",
            field=models.ImageField(
                blank=True,
                help_text="Large icon representing the asset",
                null=True,
                storage=django_s3_storage.storage.S3Storage(
                    aws_s3_bucket_name="django-images-testnet"
                ),
                upload_to="uploads/currencies_large",
            ),
        ),
    ]
