# Generated by Django 4.1.4 on 2023-02-02 15:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "walletapp",
            "0016_remove_transactions_check_transaction_status_consistency_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="transactions",
            name="inbound_invoice",
            field=models.CharField(
                blank=True,
                help_text="Inbound Taro invoice",
                max_length=5000,
                null=True,
                unique=True,
            ),
        ),
    ]
