# Generated by Django 4.1.4 on 2023-02-02 16:38

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "walletapp",
            "0020_remove_transactions_check_transaction_status_consistency_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="currencies",
            name="supply",
            field=models.IntegerField(
                blank=True,
                default=1000000,
                help_text="Total supply of the asset if minted",
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(4294967296),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="transactions",
            name="amount",
            field=models.IntegerField(
                default=0,
                help_text="Currency amount",
                null=True,
                validators=[django.core.validators.MinValueValidator(1)],
            ),
        ),
    ]
