# Generated by Django 4.1.4 on 2023-02-02 20:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("walletapp", "0021_alter_currencies_supply_alter_transactions_amount"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transactions",
            name="amount",
            field=models.IntegerField(
                default=0,
                help_text="Currency amount",
                null=True,
                validators=[django.core.validators.MinValueValidator(0)],
            ),
        ),
    ]
