# Generated by Django 4.1.4 on 2023-02-07 12:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "walletapp",
            "0025_remove_transactions_check_transaction_status_consistency_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="currencies",
            name="acronym",
            field=models.CharField(
                help_text="Asset acronym represented as 1 to 5 letters. e.g. ETH, BTC",
                max_length=5,
                validators=[
                    django.core.validators.RegexValidator(
                        "^[0-9a-zA-Z]*$", "Only alphanumeric characters are allowed."
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="currencies",
            name="description",
            field=models.CharField(
                default="",
                help_text=(
                    "Short description of the asset, include founder contact"
                    " information, explain purpose of this currency - it is a"
                    " stablecoin? a pegged coin ? "
                ),
                max_length=1000,
            ),
        ),
        migrations.AlterField(
            model_name="currencies",
            name="genesis_bootstrap_info",
            field=models.CharField(
                default="",
                help_text=(
                    "Genesis bootstrap info of the asset. Required for creating an"
                    " invoice."
                ),
                max_length=1000000,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="currencies",
            name="is_nft",
            field=models.BooleanField(
                blank=True,
                default=False,
                help_text="Indicates if the asset is a NFT or not",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="currencies",
            name="status",
            field=models.CharField(
                choices=[
                    ("submitted_for_minting", "Submitted for minting"),
                    ("minting", "Minting"),
                    ("minted", "Minted"),
                ],
                default="",
                help_text="Status of the minting transaction",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="currencies",
            name="supply",
            field=models.IntegerField(
                blank=True,
                default=1,
                help_text="Total supply of the asset once minted",
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(4294967296),
                ],
            ),
        ),
    ]
