# Generated by Django 4.1.4 on 2023-02-07 15:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("walletapp", "0027_alter_currencies_genesis_bootstrap_info"),
    ]

    operations = [
        migrations.AlterField(
            model_name="currencies",
            name="description",
            field=models.CharField(
                default="",
                help_text=(
                    "Short description of the asset, include founder contact"
                    " information, explain purpose of this currency - it is a"
                    " stablecoin? a pegged coin ? "
                ),
                max_length=200,
            ),
        ),
        migrations.AlterField(
            model_name="currencies",
            name="genesis_bootstrap_info",
            field=models.CharField(
                default="",
                help_text=(
                    "Genesis bootstrap info of the asset. Required for creating an"
                    " invoice."
                ),
                max_length=2000,
                unique=True,
            ),
        ),
    ]
