# Generated by Django 4.1.4 on 2023-02-07 18:38

import django.contrib.postgres.indexes
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("walletapp", "0030_alter_currencies_genesis_bootstrap_info"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="transactions",
            index=django.contrib.postgres.indexes.HashIndex(
                fields=["invoice_inbound"], name="walletapp_t_invoice_5f7be8_hash"
            ),
        ),
        migrations.AddIndex(
            model_name="transactions",
            index=django.contrib.postgres.indexes.HashIndex(
                fields=["invoice_outbound"], name="walletapp_t_invoice_504f36_hash"
            ),
        ),
    ]
