# Generated by Django 4.1.4 on 2023-02-07 18:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("walletapp", "0031_transactions_walletapp_t_invoice_5f7be8_hash_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transactions",
            name="invoice_inbound",
            field=models.CharField(
                blank=True, help_text="Inbound Taro invoice", max_length=5000, null=True
            ),
        ),
        migrations.AlterField(
            model_name="transactions",
            name="invoice_outbound",
            field=models.CharField(
                blank=True,
                help_text="Outbound Taro invoice",
                max_length=5000,
                null=True,
            ),
        ),
    ]
