# Generated by Django 4.1.4 on 2023-02-08 17:46

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("walletapp", "0032_alter_transactions_invoice_inbound_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transactions",
            name="amount",
            field=models.IntegerField(
                default=0,
                help_text="Currency amount",
                validators=[django.core.validators.MinValueValidator(0)],
            ),
        ),
        migrations.AlterField(
            model_name="transactions",
            name="currency",
            field=models.ForeignKey(
                blank=True,
                default=1,
                help_text="Transaction currency",
                on_delete=django.db.models.deletion.PROTECT,
                to="walletapp.currencies",
            ),
        ),
    ]
