# Generated by Django 4.1.4 on 2023-02-10 16:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("walletapp", "0033_alter_transactions_amount_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="transactions",
            name="balance",
            field=models.IntegerField(
                default=0,
                help_text="Balance at the time of purchase",
                validators=[django.core.validators.MinValueValidator(0)],
            ),
        ),
        migrations.AddField(
            model_name="transactions",
            name="pending_balance",
            field=models.IntegerField(
                default=0,
                help_text="Pending balance at the time of transaction",
                validators=[django.core.validators.MinValueValidator(0)],
            ),
        ),
    ]
