# Generated by Django 4.1.4 on 2023-02-12 16:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("walletapp", "0034_transactions_balance_transactions_pending_balance"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="transactions",
            name="balance",
        ),
        migrations.RemoveField(
            model_name="transactions",
            name="pending_balance",
        ),
        migrations.AlterField(
            model_name="currencies",
            name="status",
            field=models.CharField(
                choices=[
                    (
                        "waiting_for_miting_transaction",
                        "Waiting for minting transaction",
                    ),
                    ("submitted_for_minting", "Submitted for minting"),
                    ("minting", "Minting"),
                    ("minted", "Minted"),
                ],
                default="",
                help_text="Status of the minting transaction",
                max_length=50,
            ),
        ),
    ]
