# Generated by Django 4.1.4 on 2023-02-10 12:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("walletapp", "0034_alter_transactions_currency_pricehistory_listings"),
    ]

    operations = [
        migrations.AlterField(
            model_name="listings",
            name="price_sat",
            field=models.IntegerField(
                blank=True,
                default=0,
                help_text="Price to sell the asset for",
                null=True,
                validators=[django.core.validators.MinValueValidator(1)],
            ),
        ),
        migrations.AlterField(
            model_name="transactions",
            name="amount",
            field=models.IntegerField(
                default=0,
                help_text="Currency amount",
                validators=[django.core.validators.MinValueValidator(1)],
            ),
        ),
    ]
