# Generated by Django 4.1.4 on 2023-02-13 09:26

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("walletapp", "0035_alter_listings_price_sat_alter_transactions_amount"),
        ("walletapp", "0035_remove_transactions_balance_and_more"),
    ]

    operations = []
