# Generated by Django 4.1.4 on 2023-02-13 09:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("walletapp", "0036_merge_20230213_0926"),
    ]

    operations = [
        migrations.AddField(
            model_name="transactions",
            name="associated_exchange_transaction",
            field=models.ForeignKey(
                blank=True,
                help_text="Associated exchange transaction",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="exchange_transaction",
                to="walletapp.transactions",
            ),
        ),
        migrations.AlterField(
            model_name="transactions",
            name="status",
            field=models.CharField(
                choices=[
                    (
                        "inbound_invoice_waiting_for",
                        "Waiting for inbound invoice to be generated",
                    ),
                    (
                        "inbound_invoice_generated",
                        "Inbound invoice was generated, waiting for it to be paid",
                    ),
                    ("inbound_invoice_paid", "Inbound invoice was successfully paid"),
                    (
                        "outbound_invoice_received",
                        "Outbound invoice is waiting to be paid",
                    ),
                    ("outbound_invoice_paid", "Outbound invoice paid"),
                    ("placeholder_fee", "Placeholder fee, real amount will be added"),
                    ("fee_paid", "Fee paid"),
                    ("minting_submitted", "Currency submitted for minting"),
                    ("minting", "Currency is minting"),
                    ("tx_created", "Minting transaction created"),
                    ("minted", "Minting transaction was completed"),
                    ("internal_started", "Internal transaction submitted"),
                    ("internal_finished", "Internal transaction finished"),
                    ("exchange_started", "Exchange transaction submitted"),
                    ("exchange_finished", "Exchange transaction finished"),
                    ("error", "Error"),
                ],
                default="",
                help_text="Transaction status",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="transactions",
            name="type",
            field=models.CharField(
                choices=[
                    ("user", "User Transaction"),
                    ("internal", "Internal Transaction"),
                    ("fee", "Fee"),
                    ("minting", "Minting transaction"),
                    ("exchange_sat", "Exchange - Bitcoin currency"),
                    ("exchange_taro", "Exchange - Taro currency"),
                ],
                default="",
                help_text="Transaction type",
                max_length=50,
            ),
        ),
    ]
