# Generated by Django 4.1.4 on 2023-02-13 13:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "walletapp",
            "0039_remove_transactions_check_transaction_status_consistency_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="pricehistory",
            name="currency",
            field=models.ForeignKey(
                blank=True,
                help_text="Currency for sale",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="walletapp.currencies",
                unique=True,
            ),
        ),
    ]
