# Generated by Django 4.1.4 on 2023-04-05 10:42

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("walletapp", "0041_remove_pricehistory_time_stamp_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pricehistory",
            name="currency",
            field=models.ForeignKey(
                blank=True,
                help_text="Currency for sale",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="walletapp.currencies",
            ),
        ),
        migrations.AlterField(
            model_name="pricehistory",
            name="price_sat",
            field=models.IntegerField(
                blank=True,
                default=0,
                help_text="Currency price",
                validators=[django.core.validators.MinValueValidator(0)],
            ),
        ),
    ]
