# Generated by Django 4.1.4 on 2023-06-19 17:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("walletapp", "0042_alter_pricehistory_currency_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="currencies",
            name="genesis_bootstrap_info",
        ),
        migrations.AddField(
            model_name="currencies",
            name="asset_id",
            field=models.CharField(
                default="",
                help_text="Id of the asset. Required for creating an invoice.",
                max_length=50000,
            ),
        ),
        migrations.AlterField(
            model_name="currencies",
            name="status",
            field=models.CharField(
                choices=[
                    (
                        "waiting_for_miting_transaction",
                        "Waiting for minting transaction",
                    ),
                    ("submitted_for_minting", "Submitted for minting"),
                    ("minting", "Minting"),
                    ("minted", "Minted"),
                    ("waiting_for_meta_data", "Waiting for minting transaction"),
                    ("minted", "Minted"),
                ],
                default="",
                help_text="Status of the minting transaction",
                max_length=50,
            ),
        ),
    ]
