# Generated by Django 4.1.4 on 2023-09-12 23:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "walletapp",
            "0045_remove_transactions_check_transaction_status_consistency_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="pricehistory",
            name="price_sat",
            field=models.FloatField(
                blank=True,
                default=0,
                help_text="Currency price",
                validators=[django.core.validators.MinValueValidator(0)],
            ),
        ),
    ]
