# Generated by Django 4.1.4 on 2023-09-13 08:27

import django.contrib.postgres.indexes
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("walletapp", "0046_alter_pricehistory_price_sat"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="pricehistory",
            options={"ordering": ["-created_timestamp"]},
        ),
        migrations.AddIndex(
            model_name="pricehistory",
            index=django.contrib.postgres.indexes.HashIndex(
                fields=["currency"], name="walletapp_p_currenc_7d59fb_hash"
            ),
        ),
        migrations.AddIndex(
            model_name="pricehistory",
            index=django.contrib.postgres.indexes.HashIndex(
                fields=["period"], name="walletapp_p_period_6d7905_hash"
            ),
        ),
        migrations.AddIndex(
            model_name="pricehistory",
            index=django.contrib.postgres.indexes.HashIndex(
                fields=["created_timestamp"], name="walletapp_p_created_8764ba_hash"
            ),
        ),
        migrations.AddIndex(
            model_name="pricehistory",
            index=models.Index(
                fields=["currency", "period", "created_timestamp"],
                name="walletapp_p_currenc_3950a9_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="pricehistory",
            index=models.Index(
                fields=["currency", "period"], name="walletapp_p_currenc_6a9dec_idx"
            ),
        ),
    ]
