# Generated by Django 4.1.4 on 2023-11-18 20:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("walletapp", "0057_collections_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ControlTable",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "parameter_name",
                    models.CharField(
                        default="",
                        help_text="Name of the control parameter",
                        max_length=50,
                    ),
                ),
                (
                    "parameter_value",
                    models.IntegerField(
                        default=0, help_text="Value of the control parameter"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ExternalInfoTable",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "variable_name",
                    models.CharField(
                        default="", help_text="Name of the variable", max_length=50
                    ),
                ),
                (
                    "variable_value",
                    models.IntegerField(default=0, help_text="Value of the variable"),
                ),
            ],
        ),
        migrations.AddField(
            model_name="currencies",
            name="holders_num",
            field=models.IntegerField(
                blank=True,
                default=0,
                help_text="Number of holders of the assets",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="currencies",
            name="orders_num",
            field=models.IntegerField(
                blank=True,
                default=0,
                help_text="Number of orders on the assets",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="currencies",
            name="transaction_num",
            field=models.IntegerField(
                blank=True,
                default=0,
                help_text="Number of transactions done with the asset in last 1 day",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="currencies",
            name="volume",
            field=models.IntegerField(
                blank=True,
                default=0,
                help_text="Volume of the asset traded in last 1 day",
                null=True,
            ),
        ),
    ]
