# Generated by Django 4.1.4 on 2023-11-19 18:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("walletapp", "0059_alter_currencies_picture_large_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="currencies",
            options={
                "ordering": [
                    "-volume",
                    "-transaction_num",
                    "-orders_num",
                    "-holders_num",
                ]
            },
        ),
        migrations.AddField(
            model_name="controltable",
            name="created_timestamp",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="externalinfotable",
            name="created_timestamp",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
