# Generated by Django 4.1.4 on 2023-11-26 15:47

import django_s3_storage.storage
import walletapp.utils
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("walletapp", "0062_transactions_balance_transactions_pending_balance"),
    ]

    operations = [
        migrations.AddField(
            model_name="collections",
            name="holders_num",
            field=models.IntegerField(
                blank=True,
                default=0,
                help_text="Number of holders of the collection",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="collections",
            name="orders_num",
            field=models.IntegerField(
                blank=True,
                default=0,
                help_text="Number of orders on the collection",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="collections",
            name="transaction_num",
            field=models.IntegerField(
                blank=True,
                default=0,
                help_text=(
                    "Number of transactions done with the collection in last 1 hour"
                ),
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="collections",
            name="volume",
            field=models.IntegerField(
                blank=True,
                default=0,
                help_text="Volume of the collection traded in last 1 hour",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="currencies",
            name="price_change",
            field=models.IntegerField(
                blank=True,
                default=0,
                help_text="Price change in the past 1 hour",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="currencies",
            name="picture_large",
            field=models.ImageField(
                blank=True,
                help_text="Small icon representing the asset",
                null=True,
                storage=django_s3_storage.storage.S3Storage(
                    aws_s3_bucket_name="django-images-testnet"
                ),
                upload_to=walletapp.utils.get_media_path_large,
            ),
        ),
        migrations.AlterField(
            model_name="currencies",
            name="picture_orig",
            field=models.ImageField(
                blank=True,
                help_text=(
                    "Image representing the asset. Please upload a square image about"
                    " 800x800 in size. Images will be rescaled."
                ),
                null=True,
                storage=django_s3_storage.storage.S3Storage(
                    aws_s3_bucket_name="django-images-testnet"
                ),
                upload_to=walletapp.utils.get_media_path_orig,
            ),
        ),
        migrations.AlterField(
            model_name="currencies",
            name="picture_small",
            field=models.ImageField(
                blank=True,
                help_text="Large icon representing the asset",
                null=True,
                storage=django_s3_storage.storage.S3Storage(
                    aws_s3_bucket_name="django-images-testnet"
                ),
                upload_to=walletapp.utils.get_media_path_small,
            ),
        ),
    ]
