# Generated by Django 4.1.4 on 2024-01-12 09:22

import django.contrib.postgres.indexes
import django_s3_storage.storage
import walletapp.utils
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("walletapp", "0063_collections_holders_num_collections_orders_num_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="collections",
            options={
                "ordering": [
                    "-holders_num",
                    "-transaction_num",
                    "-orders_num",
                    "-volume",
                ]
            },
        ),
        migrations.AlterField(
            model_name="currencies",
            name="picture_large",
            field=models.ImageField(
                blank=True,
                help_text="Small icon representing the asset",
                null=True,
                storage=django_s3_storage.storage.S3Storage(
                    aws_s3_bucket_name="django-images-prod"
                ),
                upload_to=walletapp.utils.get_media_path_large,
            ),
        ),
        migrations.AlterField(
            model_name="currencies",
            name="picture_orig",
            field=models.ImageField(
                blank=True,
                help_text=(
                    "Image representing the asset. Please upload a square image about"
                    " 800x800 in size. Images will be rescaled."
                ),
                null=True,
                storage=django_s3_storage.storage.S3Storage(
                    aws_s3_bucket_name="django-images-prod"
                ),
                upload_to=walletapp.utils.get_media_path_orig,
            ),
        ),
        migrations.AlterField(
            model_name="currencies",
            name="picture_small",
            field=models.ImageField(
                blank=True,
                help_text="Large icon representing the asset",
                null=True,
                storage=django_s3_storage.storage.S3Storage(
                    aws_s3_bucket_name="django-images-prod"
                ),
                upload_to=walletapp.utils.get_media_path_small,
            ),
        ),
        migrations.AddIndex(
            model_name="currencies",
            index=django.contrib.postgres.indexes.HashIndex(
                fields=["name"], name="walletapp_c_name_f57836_hash"
            ),
        ),
        migrations.AddIndex(
            model_name="currencies",
            index=django.contrib.postgres.indexes.HashIndex(
                fields=["collection"], name="walletapp_c_collect_f4cc85_hash"
            ),
        ),
        migrations.AddIndex(
            model_name="currencies",
            index=django.contrib.postgres.indexes.HashIndex(
                fields=["asset_id"], name="walletapp_c_asset_i_5fdd0c_hash"
            ),
        ),
        migrations.AddIndex(
            model_name="currencies",
            index=django.contrib.postgres.indexes.HashIndex(
                fields=["acronym"], name="walletapp_c_acronym_db5277_hash"
            ),
        ),
        migrations.AddIndex(
            model_name="currencies",
            index=django.contrib.postgres.indexes.HashIndex(
                fields=["owner"], name="walletapp_c_owner_i_26190b_hash"
            ),
        ),
        migrations.AddIndex(
            model_name="currencies",
            index=django.contrib.postgres.indexes.HashIndex(
                fields=["is_nft"], name="walletapp_c_is_nft_5c94f5_hash"
            ),
        ),
        migrations.AddIndex(
            model_name="currencies",
            index=django.contrib.postgres.indexes.HashIndex(
                fields=["status"], name="walletapp_c_status_b727d2_hash"
            ),
        ),
    ]
