# Generated by Django 4.1.4 on 2024-01-12 12:04

import django_s3_storage.storage
import walletapp.utils
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("walletapp", "0065_alter_currencies_picture_large_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="collections",
            options={"ordering": ["-holders_num"]},
        ),
        migrations.AlterModelOptions(
            name="currencies",
            options={"ordering": ["-holders_num"]},
        ),
        migrations.AlterField(
            model_name="currencies",
            name="picture_large",
            field=models.ImageField(
                blank=True,
                help_text="Small icon representing the asset",
                null=True,
                storage=django_s3_storage.storage.S3Storage(
                    aws_s3_bucket_name="django-images-prod"
                ),
                upload_to=walletapp.utils.get_media_path_large,
            ),
        ),
        migrations.AlterField(
            model_name="currencies",
            name="picture_orig",
            field=models.ImageField(
                blank=True,
                help_text=(
                    "Image representing the asset. Please upload a square image about"
                    " 800x800 in size. Images will be rescaled."
                ),
                null=True,
                storage=django_s3_storage.storage.S3Storage(
                    aws_s3_bucket_name="django-images-prod"
                ),
                upload_to=walletapp.utils.get_media_path_orig,
            ),
        ),
        migrations.AlterField(
            model_name="currencies",
            name="picture_small",
            field=models.ImageField(
                blank=True,
                help_text="Large icon representing the asset",
                null=True,
                storage=django_s3_storage.storage.S3Storage(
                    aws_s3_bucket_name="django-images-prod"
                ),
                upload_to=walletapp.utils.get_media_path_small,
            ),
        ),
        migrations.AddIndex(
            model_name="currencies",
            index=models.Index(
                fields=["status", "is_nft"], name="walletapp_c_status_d819b3_idx"
            ),
        ),
    ]
