# Generated by Django 4.1.4 on 2024-01-12 12:17

import django.contrib.postgres.indexes
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "walletapp",
            "0066_alter_collections_options_alter_currencies_options_and_more",
        ),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="currencies",
            name="walletapp_c_status_d819b3_idx",
        ),
        migrations.AddIndex(
            model_name="currencies",
            index=django.contrib.postgres.indexes.HashIndex(
                fields=["holders_num"], name="walletapp_c_holders_d41e23_hash"
            ),
        ),
        migrations.AddIndex(
            model_name="currencies",
            index=models.Index(
                fields=["status", "is_nft", "holders_num"],
                name="walletapp_c_status_4baece_idx",
            ),
        ),
    ]
