# Generated by Django 4.1.4 on 2024-01-21 02:32

import django.contrib.postgres.indexes
import django.db.models.deletion
import django_s3_storage.storage
import walletapp.utils
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("walletapp", "0067_remove_currencies_walletapp_c_status_d819b3_idx_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="currencies",
            options={"ordering": ["-holders_num", "-orders_num"]},
        ),
        migrations.AlterField(
            model_name="currencies",
            name="picture_large",
            field=models.ImageField(
                blank=True,
                help_text="Small icon representing the asset",
                null=True,
                storage=django_s3_storage.storage.S3Storage(
                    aws_s3_bucket_name="django-images-testnet"
                ),
                upload_to=walletapp.utils.get_media_path_large,
            ),
        ),
        migrations.AlterField(
            model_name="currencies",
            name="picture_orig",
            field=models.ImageField(
                blank=True,
                help_text=(
                    "Image representing the asset. Please upload a square image about"
                    " 800x800 in size. Images will be rescaled."
                ),
                null=True,
                storage=django_s3_storage.storage.S3Storage(
                    aws_s3_bucket_name="django-images-testnet"
                ),
                upload_to=walletapp.utils.get_media_path_orig,
            ),
        ),
        migrations.AlterField(
            model_name="currencies",
            name="picture_small",
            field=models.ImageField(
                blank=True,
                help_text="Large icon representing the asset",
                null=True,
                storage=django_s3_storage.storage.S3Storage(
                    aws_s3_bucket_name="django-images-testnet"
                ),
                upload_to=walletapp.utils.get_media_path_small,
            ),
        ),
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "read",
                    models.BooleanField(
                        blank=True,
                        default=False,
                        help_text="Indicates if the notification was read",
                        null=True,
                    ),
                ),
                (
                    "message",
                    models.CharField(
                        default="", help_text="Message to display", max_length=50
                    ),
                ),
                (
                    "object_name",
                    models.CharField(
                        choices=[
                            ("t", "Transactions"),
                            ("w", "Listings"),
                            ("c", "Currencies"),
                        ],
                        default="",
                        help_text="Object related to the message",
                        max_length=100,
                    ),
                ),
                (
                    "object_id",
                    models.IntegerField(
                        default=0, help_text="Object id related to the message"
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        blank=True,
                        choices=[("e", "error"), ("w", "warning"), ("s", "success")],
                        help_text="Notification type",
                        max_length=50,
                        null=True,
                    ),
                ),
                ("created_timestamp", models.DateTimeField(auto_now_add=True)),
                ("updated_timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "destination_user",
                    models.ForeignKey(
                        blank=True,
                        help_text="User targeted by the notification",
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["read", "-created_timestamp"],
            },
        ),
        migrations.AddIndex(
            model_name="notification",
            index=django.contrib.postgres.indexes.HashIndex(
                fields=["destination_user"], name="walletapp_n_destina_66476c_hash"
            ),
        ),
        migrations.AddIndex(
            model_name="notification",
            index=django.contrib.postgres.indexes.HashIndex(
                fields=["read"], name="walletapp_n_read_bec513_hash"
            ),
        ),
        migrations.AddIndex(
            model_name="notification",
            index=django.contrib.postgres.indexes.HashIndex(
                fields=["created_timestamp"], name="walletapp_n_created_8638e7_hash"
            ),
        ),
        migrations.AddIndex(
            model_name="notification",
            index=models.Index(
                fields=["destination_user", "read", "created_timestamp"],
                name="walletapp_n_destina_ae6e09_idx",
            ),
        ),
    ]
