# Generated by Django 4.1.4 on 2024-01-21 18:33

import django.contrib.postgres.indexes
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("walletapp", "0068_alter_currencies_options_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Notifications",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "read",
                    models.BooleanField(
                        blank=True,
                        default=False,
                        help_text="Indicates if the notification was read",
                        null=True,
                    ),
                ),
                (
                    "message",
                    models.CharField(
                        default="", help_text="Message to display", max_length=50
                    ),
                ),
                (
                    "object_name",
                    models.CharField(
                        choices=[
                            ("t", "Transactions"),
                            ("w", "Listings"),
                            ("c", "Currencies"),
                        ],
                        default="",
                        help_text="Object related to the message",
                        max_length=100,
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        blank=True,
                        choices=[("e", "error"), ("w", "warning"), ("s", "success")],
                        help_text="Notifications type",
                        max_length=50,
                        null=True,
                    ),
                ),
                ("created_timestamp", models.DateTimeField(auto_now_add=True)),
                ("updated_timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "destination_user",
                    models.ForeignKey(
                        blank=True,
                        help_text="User targeted by the notification",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="target_user",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "listing",
                    models.ForeignKey(
                        blank=True,
                        help_text="Listing associated with the notification",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="walletapp.listings",
                    ),
                ),
                (
                    "transaction",
                    models.ForeignKey(
                        blank=True,
                        help_text="Transaction associated with the notification",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="walletapp.transactions",
                    ),
                ),
            ],
            options={
                "ordering": ["read", "-created_timestamp"],
            },
        ),
        migrations.DeleteModel(
            name="Notification",
        ),
        migrations.AddIndex(
            model_name="notifications",
            index=django.contrib.postgres.indexes.HashIndex(
                fields=["destination_user"], name="walletapp_n_destina_63290f_hash"
            ),
        ),
        migrations.AddIndex(
            model_name="notifications",
            index=django.contrib.postgres.indexes.HashIndex(
                fields=["read"], name="walletapp_n_read_cedcae_hash"
            ),
        ),
        migrations.AddIndex(
            model_name="notifications",
            index=django.contrib.postgres.indexes.HashIndex(
                fields=["created_timestamp"], name="walletapp_n_created_42782e_hash"
            ),
        ),
        migrations.AddIndex(
            model_name="notifications",
            index=models.Index(
                fields=["destination_user", "read", "created_timestamp"],
                name="walletapp_n_destina_48896d_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="notifications",
            constraint=models.UniqueConstraint(
                fields=(
                    "transaction",
                    "listing",
                    "object_name",
                    "destination_user",
                    "type",
                ),
                name="one_notification_per_object_per_user",
            ),
        ),
    ]
