# Generated by Django 4.1.4 on 2024-01-21 18:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("walletapp", "0069_notifications_delete_notification_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notifications",
            name="message",
            field=models.CharField(
                default="", help_text="Message to display", max_length=200
            ),
        ),
    ]
