# Generated by Django 4.1.4 on 2024-01-22 01:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("walletapp", "0070_alter_notifications_message"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notifications",
            name="listing",
            field=models.ForeignKey(
                blank=True,
                help_text="Listing associated with the notification",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="walletapp.listings",
            ),
        ),
        migrations.AlterField(
            model_name="notifications",
            name="transaction",
            field=models.ForeignKey(
                blank=True,
                help_text="Transaction associated with the notification",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="walletapp.transactions",
            ),
        ),
    ]
